### PR TITLE
Parse the wav_filesize as float

### PR DESCRIPTION
**Pull request by Jendker**
Allows the backward compatibility with the csv files.

### CODE REVIEW

**Comment by lissyx** [comment]
> Allows the backward compatibility with the csv files.

Do you mind elaborating on that? There's no good reason a size would be a float.

**Comment by Jendker** [comment]
I haven't found in the documentation any information what should be the base of the `wav_filesize`, so one may select arbitrary base, for example the kB. In this case the specification of the size as a float is reasonable.

So I think it makes sense to either specify in the docus what should be the specific structure of the .csv files to avoid the confusion or to merge this change.

**Comment by lissyx** [comment]
> I haven't found in the documentation any information what should be the base of the `wav_filesize`, so one may select arbitrary base, for example the kB. In this case the specification of the size as a float is reasonable.
> 
> So I think it makes sense to either specify in the docus what should be the specific structure of the .csv files to avoid the confusion or to merge this change.

If you take a look at all the importers, it's in bytes. It is so obvious we never even thought about requiring documenting that, but if you think it is important, we welcome a PR to fix that!

**Comment by lissyx** [comment]
> it makes sense to either specify in the docus what should be the specific structure of the .csv files to avoid the confusion

Let's take this road, I'll close this PR.

**Comment by Jendker** [comment]
Added new PR https://github.com/mozilla/STT/pull/3258

**Pull request closed without merging**
